frontend:
  - "lib/**"

backend:
  - "server/**"

bug:
  - ".github/ISSUE_TEMPLATE/bug_report.md"

enhancement:
  - ".github/ISSUE_TEMPLATE/feature_request.md"

firebase:
  - "lib/firebase/**"

ui/ux:
  - "lib/ui/**"